language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coveralls
script:
  - pipenv run pytest
after_success:
  - coveralls
notifications:
  email: false
  slack:
    rooms:
      - secure: fdXu/ThituJ6wFr9dgQGGVXKwmN/IWbygP+8ICiI6Y92XZlBMwfY/HR+KjD05SEECmLVbfDN+hZf9OcVKLAu8LsKt2ICIocFM0YyJz4OEJ8UGCFD2RDEG8UrZ6Ga4eLI4Cz0FT5pkVu8bULNroJD7ocJKVLHQXgYSQSFhPc7t4g2NG9oB/eMGkOqxb4tQ3rhf9mEouxcY1igix0GMeEt/hr/CHkKMiUxFMHXRADzHuheGdAvaQtx8rTkpAocTqMNERKWUNad/1F2oUgvuRdhOSOF2DRblf6kw8RZASFqPKCXpRyojDx2A+g4pIcu8u67Htf+thbFckMkEm06uBjc1jvCijvLQ1LTdE4Ka0Z67N85x6TiUobXkoO2UdiVT0dEDixc5ruX0mj6UJ/XX+A3JDd3H+pxxxYigooTSdeAE+GAOVi9FCwbH9wzxBlzAOOtXd132Qnmy9dqC23b5N1ZZ7P46Mcc8GhSgslN1CRowgfMTQ1XYtYryaYBpTa/oXFBTj+S3AtU5A3FHsL78wMuq3oCaWjJ2n5VPQUtbEq8u7eEfATj8n9A43sGDwt69O2DHzMEoQ9yumTmbV8MVcynBHiiyigxqAlfiUE0cKIPHsLHsud00IqGJhE6GXyc3RzavaavM3T0PznWvoEF3eGYuGISBEdKscTlo4u5r/mLCTk=
    on_success: change
    on_failure: always
    on_pull_requests: true
deploy:
  provider: pypi
  user: brouberol
  password:
    secure: Svi83cuclzCGEheRKFtG//6GP4RHosFtjEBAwED/EFy7eU7YlJhjlNDfjzXlYWBup5HmZCOalSIIjLBVEbK2HDD3dqrVA9bp8LMv2xGPc5Lp5h02uNpYfqdyf3Ut6AzM5iKy0Sj7DfRdd3Dqyl2S4akcH9CvkeNWFyBYuCp4jD8HMqRvn87k1iI9d8ceJojikoLd2NHNnBHQvhLj7+o7589qW3+UcjfoIOGPz4181BO0rCoJkstxD8aH8U8zEKLTgpp1/lvHweJ7SbBpchWzAebetfLEFXz/UiVDT4CUrwQFC4W1f43zYjtaivlDfApxq0TACwzLpmO9zj/ig0Zuv+uNTBhA+sgYktiyrkbC3pE+cL1MIYMb21sL5q+ZZhTblzFmD9nnONyYmGx40XKHGZTzXt6UqoB5lM/Yszxh9kUBYPjlviQsEYm7CP3xI7cdhJ1/JsoSDYhyXk2N1ZwQlNKoITzb+M8scvX+Pah3LXdSysQRnPOr+JlgkCmQFDs8YDB4pDBYnASRJWHfDZYYevya6M2WnBPMBCFw4FX4Ilnk2RrIZVMivWmLY04WhZS9NDnI+nr0Nc+G2DDVAzxfqoj/cVDOOpu8re/a+erbTXh34k0Iie9IuxxfdHwH5uJA/YdKIK/pPyP91/H2ObZ7trFx9lvqq/BwjSXXbBx/zXc=
  on:
    tags: true
